#!/bin/bash
#SBATCH --partition=gpu_a100
#SBATCH --gpus=2
#SBATCH --cpus-per-task=16
#SBATCH --job-name=img2text_aligner
#SBATCH --output=/home/azywot/FOMO/stable-diffusion-v2/outputs/jobs/img2text_aligner_%A.out
#SBATCH --time=06:00:00
#SBATCH --mem=80G
#SBATCH --hint=nomultithread

echo "✅ Job started at: $(date)"
module purge
module load 2024
module load CUDA/11.7.0

cd /home/azywot/FOMO/stable-diffusion-v2
source .venv/bin/activate

export HF_DATASETS_CACHE="/scratch-shared/holy-triangle/huggingface_datasets"
export TRANSFORMERS_CACHE="/scratch-shared/holy-triangle/huggingface_models"

# Run the training script
python scripts/vcf/train_img2text_aligner.py \
  --datasets 'flickr30k' \
  --loss cosine \
  --batch_size 128 \
  --epochs 10 \
  --lr 1e-4 \
  --device cuda \
  --wandb_project text-image-aligner \
  --model_path weights/img2text_aligner/flickr30k_cosine/model.pth \
  --save_every 5
